# Generated by Django 2.0.6 on 2018-06-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=200)),
                ('District', models.CharField(max_length=200)),
                ('Crop', models.CharField(max_length=200)),
                ('Year', models.CharField(max_length=200)),
                ('Season', models.CharField(max_length=200)),
                ('Area', models.CharField(max_length=200)),
                ('Production', models.CharField(max_length=200)),
                ('Yield', models.CharField(max_length=200)),
                ('Yield_Units', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['State'],
            },
        ),
    ]
