# Generated by Django 2.0.6 on 2018-06-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_combine'),
    ]

    operations = [
        migrations.CreateModel(
            name='soil_health_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('sub_district', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('sample_no', models.CharField(max_length=200)),
                ('farmer_name', models.CharField(max_length=200)),
                ('land_area', models.CharField(max_length=200)),
                ('khasra_no_dag_no', models.CharField(max_length=200)),
                ('survey_no', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('ph', models.CharField(max_length=200)),
                ('ec', models.CharField(max_length=200)),
                ('oc', models.CharField(max_length=200)),
                ('n', models.CharField(max_length=200)),
                ('p', models.CharField(max_length=200)),
                ('k', models.CharField(max_length=200)),
                ('s', models.CharField(max_length=200)),
                ('zn', models.CharField(max_length=200)),
                ('fe', models.CharField(max_length=200)),
                ('cu', models.CharField(max_length=200)),
                ('mn', models.CharField(max_length=200)),
                ('b', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'soil_health_card',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AlterModelOptions(
            name='combine',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
