# Generated by Django 2.0.6 on 2018-06-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_source_irrigated'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='soil_health_card',
            table='soil_health_card_india',
        ),
    ]
